
/**
 * Matt Rutherford
 *
 */
/**
 *
 * @author rutherford
 */
public class MainFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PrimeSpinner = new javax.swing.JSpinner();
        PrimeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FactorialSpinner = new javax.swing.JSpinner();
        FactorialTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        YearSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        YearTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Operations");
        setBackground(new java.awt.Color(226, 254, 226));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Prime");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Prime #Count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        PrimeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PrimeSpinnerStateChanged(evt);
            }
        });
        getContentPane().add(PrimeSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 120, -1));

        PrimeTextField.setEditable(false);
        getContentPane().add(PrimeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 24, 60, -1));

        jLabel3.setText("Factorial (n!)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        FactorialSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FactorialSpinnerStateChanged(evt);
            }
        });
        getContentPane().add(FactorialSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        FactorialTextField.setEditable(false);
        getContentPane().add(FactorialTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 60, -1));

        jLabel4.setText("Factorial Result");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel5.setText("Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        YearSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                YearSpinnerStateChanged(evt);
            }
        });
        getContentPane().add(YearSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, -1));

        jLabel6.setText("Valid Leap Year");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        YearTextField.setEditable(false);
        getContentPane().add(YearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrimeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrimeSpinnerStateChanged
        int input = (int) PrimeSpinner.getValue();// Get value from Spinner
        int output;
        Prime prime = new Prime(input);
        prime.countPrimes();
        output = prime.getPrimeCount();
        PrimeTextField.setText(Integer.toString(output)); //Store value in TextField
    }//GEN-LAST:event_PrimeSpinnerStateChanged

    private void FactorialSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FactorialSpinnerStateChanged
        int input = (int) FactorialSpinner.getValue();// Get value from Spinner
        int output;
        // Call method to calculate factorial
        Factorial factorial = new Factorial(input);
        factorial.calculateFactorial();
        output = factorial.getFactorial();
        FactorialTextField.setText(Integer.toString(output)); //Store value in TextField
    }//GEN-LAST:event_FactorialSpinnerStateChanged

    private void YearSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_YearSpinnerStateChanged
        int input = (int) YearSpinner.getValue(); //Get value from Spinner
        String output = "No";
        LeapYear leapyear = new LeapYear(input);
        if (leapyear.isLeapYear())
        {
            output = "Yes";
        }
        YearTextField.setText(output);
    }//GEN-LAST:event_YearSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner FactorialSpinner;
    private javax.swing.JTextField FactorialTextField;
    private javax.swing.JSpinner PrimeSpinner;
    private javax.swing.JTextField PrimeTextField;
    private javax.swing.JSpinner YearSpinner;
    private javax.swing.JTextField YearTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
